version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PORT: ${PORT}
    #     APP_DIR: ${APP_DIR}
    # env_file: .env
    ports:
      # - ${PORT}:${PORT}
      - "8080:8080"
    environment:
      - PORT=8080
    # depends_on:
    #   - postgresql
    # container_name: digiftng-webapp-testing
